logger:
  level: debug # Log level
  
rebalance_timer: 5m  # Interval to check nodes' health

connect_timeout: 60s  # Timeout to dial node

request_timeout: 300s  # Timeout to check node health during rebalance

server:
  - address: 0.0.0.0:80

# Wallet settings
wallet:
  path: /wallet.json  # Path to wallet 
  passphrase: one  # Passphrase to decrypt wallet
