---

version: "2.4"
services:
  k6_node:
    build:
      context: .
      dockerfile: Dockerfile
    domainname: ${LOCAL_DOMAIN}
    ports:
      - 2222:2222
    hostname: k6-node
    container_name: k6-node
    restart: "no"
    networks:
      k6_node_int:
      internet:
        ipv4_address: ${IPV4_PREFIX}.102
    stop_signal: SIGKILL
    env_file: [ ".env", ".k6_node.env" ]
    volumes:
      - ./id_ed25519.pub:/root/id_ed25519.pub:rw
      - ./../../vendor/hosts:/etc/hosts

networks:
  k6_node_int:
  internet:
    external: true
    name: basenet_internet
